name: main

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-2022

    steps:
    # Checkout 
    - uses: actions/checkout@v2

    # Setup .Net 
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x

    # Restore dependencies 
    - name: Restore dependencies
      run: dotnet restore HeroCrabPluginTests/

    # Build the project 
    - name: Build
      run:  dotnet build HeroCrabPluginTests --no-restore --verbosity detailed

    # Test the project
    - name: Test
      run: dotnet test HeroCrabPluginTests --no-build --verbosity normal