name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    # Checkout 
    - uses: actions/checkout@v2

    # Setup .Net 
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x

    # Restore dependencies 
    - name: Restore dependencies
      run: dotnet restore HeroCrabPluginTests/HeroCrabPluginTests.csproj

    # Build the project 
    - name: Build
      run:  dotnet build HeroCrabPluginTests/HeroCrabPluginTests.sln --no-restore --verbosity normal

    # Test the project
    - name: Test
      run: dotnet test HeroCrabPluginTests/HeroCrabPluginTests.sln --no-build --verbosity normal
